#!/bin/sh
 
mount -t proc none /proc
mount -t sysfs none /sys
 
echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"

echo '''
      i      ii              i
    ii iii   iii             iii
    ii                       iii
    iiiiii  iiii   iiiiiiiii iii iiiii
 iiiii       ii   iii    ii  iiiii  iii
  iiii       ii   iiii       iiii   iii
    ii       ii       iiiii  iii    ii
    ii       ii          iii iii    ii
    ii      iiii  i      iii iii    ii
     i       ii      iiii    i      ii

'''
 
su fish
exec /bin/sh


